version: "3.9"
services:
    nodehub_be:
        build: .
        depends_on:
        - mysqldb
        - elasticsearch
    elasticsearch:
        image: elasticsearch:7.7.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    mysqldb:
        image: mysql:8.0
        ports:
          - "3307:3306"
        volumes:
          - mysqldb_data:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: "13091999"
          MYSQL_DATABASE: nodehub
          MYSQL_USER: hieunm27
          MYSQL_PASSWORD: "13091999"
networks:
    elknetwork:
        driver: bridge
volumes:
  mysqldb_data:
    driver: local